services:
  - type: web
    name: yolov5-flask-app
    runtime: python
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
